# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "https://github.com/CocoaPods/Old-Specs"

target 'iOS Demo' do
    pod "SVProgressHUD", :path => "../"
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS Demo

end

target 'tvOS Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tvOS Demo

end
